language: android
android:
  components:
    - platform-tools
    - tools

    - build-tools-24.0.1
    - android-23

    - sys-img-armeabi-v7a-android-23
    - sys-img-x86-android-23

script:
    - chmod +x ./gradlew
    - ./gradlew build connectedCheck